const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, 'src', 'data', 'platforms.json');
const currentData = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const newPlatforms = [
  // META-DIRECTORIES (Resources & Meta-Directories)
  { id: "scalejobs", name: "Scale.jobs", url: "https://scale.jobs", category: "Resources & Meta-Directories", type: "Resource", description: "Tools and aggregator including resume checker and salary predictor.", tags: ["Aggregator", "Tools"], aiExposure: "Low" },
  { id: "startupstash", name: "Startup Stash", url: "https://startupstash.com/job-boards", category: "Resources & Meta-Directories", type: "Resource", description: "Startup-focused job resources and tool directory favored by early-stage companies.", tags: ["Startups", "Curated"], aiExposure: "Low" },
  { id: "resourcefyi", name: "Resource.fyi", url: "https://resource.fyi", category: "Resources & Meta-Directories", type: "Resource", description: "Curated tools and job boards for remote professionals driven by community voting.", tags: ["Community", "Curated"], aiExposure: "Low" },
  { id: "alternativeto", name: "AlternativeTo", url: "https://alternativeto.net/platform/remote-work", category: "Resources & Meta-Directories", type: "Resource", description: "Find alternative software, platforms, and remote work boards verified by user reviews.", tags: ["Crowdsourced", "Reviews"], aiExposure: "Low" },
  { id: "saashub", name: "SaaSHub", url: "https://saashub.com", category: "Resources & Meta-Directories", type: "Resource", description: "Independent software directory and comparison tables for remote tools and HR boards.", tags: ["B2B", "Comparisons"], aiExposure: "Low" },
  { id: "producthunt", name: "Product Hunt", url: "https://producthunt.com/search?q=remote+jobs", category: "Resources & Meta-Directories", type: "Resource", description: "The premier launchpad for uncovering new remote job boards, matching tools, and SaaS.", tags: ["New Launches", "Tech"], aiExposure: "Low" },
  { id: "remotetools", name: "Remote Tools", url: "https://remote.tools", category: "Resources & Meta-Directories", type: "Resource", description: "Curated remote work stack, productivity tools, and community boards.", tags: ["Remote Stack", "Community"], aiExposure: "Low" },
  { id: "nodesk", name: "NoDesk", url: "https://nodesk.co", category: "Resources & Meta-Directories", type: "Resource", description: "Hand-curated guides, job boards, and resources for the modern digital nomad.", tags: ["Nomads", "Guides"], aiExposure: "Low" },
  { id: "remotefirst", name: "Remote-First", url: "https://remote-first.com", category: "Resources & Meta-Directories", type: "Resource", description: "Vetted remote company directories profiling workplace culture and hiring practices.", tags: ["Company Profiles", "Culture"], aiExposure: "Low" },
  { id: "hiringwithoutwhiteboards", name: "Hiring Without Whiteboards", url: "https://github.com/poteto/hiring-without-whiteboards", category: "Resources & Meta-Directories", type: "Resource", description: "Massive community list of companies that respect your time and don't do broken whiteboard interviews.", tags: ["Ethical Hiring", "No-Whiteboard"], aiExposure: "Low" },
  { id: "4dayweek", name: "4 Day Week", url: "https://4dayweek.io", category: "Resources & Meta-Directories", type: "Resource", description: "Dedicated to roles and companies offering a 4-day work week for ultimate work-life balance.", tags: ["Work-Life Balance", "Progressive"], aiExposure: "Low" },
  { id: "keyvalues", name: "Key Values", url: "https://keyvalues.com", category: "Resources & Meta-Directories", type: "Resource", description: "Match with engineering and remote roles based purely on company culture and deep values.", tags: ["Culture First", "Matching"], aiExposure: "Low" },
  { id: "techjobsforgood", name: "Tech Jobs for Good", url: "https://techjobsforgood.com", category: "Resources & Meta-Directories", type: "Resource", description: "Social impact roles and mission-driven remote work for ethical professionals.", tags: ["Social Impact", "Mission Driven"], aiExposure: "Low" },
  { id: "climatebase", name: "Climatebase", url: "https://climatebase.org", category: "Resources & Meta-Directories", type: "Resource", description: "The leading directory for climate tech, sustainability, and green remote jobs.", tags: ["Climate Tech", "Sustainability"], aiExposure: "Low" },
  { id: "diversifytech", name: "Diversify Tech", url: "https://diversifytech.co", category: "Resources & Meta-Directories", type: "Resource", description: "Inclusive hiring boards and resources dedicated to elevating underrepresented talent.", tags: ["Inclusive", "Diversity"], aiExposure: "Low" },
  { id: "whoishiring", name: "Who is Hiring (HN)", url: "https://whoishiring.io", category: "Resources & Meta-Directories", type: "Resource", description: "Aggregates the monthly Hacker News hiring threads into a searchable map and board.", tags: ["Y-Combinator", "Startups"], aiExposure: "Low" },
  { id: "trulyremote", name: "Truly Remote", url: "https://trulyremote.co", category: "Resources & Meta-Directories", type: "Resource", description: "Focuses strictly on roles that offer 100% location freedom without timezone constraints.", tags: ["100% Remote", "Nomad"], aiExposure: "Low" },
  
  // GENERAL JOB BOARDS
  { id: "justremote", name: "JustRemote", url: "https://justremote.co", category: "General Job Boards", type: "Work", description: "Discover hidden remote jobs from tech to customer success. Offers a premium 'Power Search'.", tags: ["Hidden Jobs", "All Fields"], aiExposure: "Medium" },
  { id: "workingnomads", name: "Working Nomads", url: "https://workingnomads.co", category: "General Job Boards", type: "Work", description: "Curated daily newsletter and job board for digital professionals seeking global roles.", tags: ["Newsletter", "Nomads"], aiExposure: "Medium" },
  { id: "remotive", name: "Remotive", url: "https://remotive.com", category: "General Job Boards", type: "Work", description: "Vetted tech and non-tech remote jobs. Features a vibrant Slack community for job seekers.", tags: ["Vetted", "Community"], aiExposure: "Medium" },
  { id: "jobspresso", name: "Jobspresso", url: "https://jobspresso.co", category: "General Job Boards", type: "Work", description: "High-quality, manually reviewed remote work postings. Heavy focus on US timezones but expanding.", tags: ["Manual Review", "High Quality"], aiExposure: "Medium" },
  { id: "dailyremote", name: "DailyRemote", url: "https://dailyremote.com", category: "General Job Boards", type: "Work", description: "Aggregator stripping noise to deliver a daily digest of fresh global remote roles.", tags: ["Aggregator", "Daily Digest"], aiExposure: "Medium" },
  { id: "virtualvocations", name: "Virtual Vocations", url: "https://virtualvocations.com", category: "General Job Boards", type: "Work", description: "Massive database of hand-screened remote jobs across all industries. Prevents scam postings.", tags: ["Screened", "Subscription Option"], aiExposure: "Medium" },
  { id: "skipthedrive", name: "SkipTheDrive", url: "https://skipthedrive.com", category: "General Job Boards", type: "Work", description: "Free remote job board with a strong emphasis on entry-level, customer service, and accounting roles.", tags: ["Entry Level", "Service"], aiExposure: "Medium" },
  { id: "ratracerebellion", name: "Rat Race Rebellion", url: "https://ratracerebellion.com", category: "General Job Boards", type: "Work", description: "Vigorously screened gig leads and WAH jobs protecting seekers from scams. Excellent for entry-level.", tags: ["Scam-Free", "Entry Level"], aiExposure: "Medium" },
  { id: "wellfound", name: "Wellfound (AngelList)", url: "https://wellfound.com", category: "General Job Boards", type: "Work", description: "The premier board for startup jobs. Features transparent salary and equity upfront.", tags: ["Startups", "Transparent Pay"], aiExposure: "Low" },
  { id: "remoteco", name: "Remote.co", url: "https://remote.co", category: "General Job Boards", type: "Work", description: "Fully remote roles across all industries. Features deep Q&As with hiring companies.", tags: ["All Industries", "Company Q&A"], aiExposure: "Medium" },
  { id: "outsourcely", name: "Outsourcely", url: "https://outsourcely.com", category: "General Job Boards", type: "Work", description: "Focuses entirely on long-term remote relationships rather than short freelance gigs.", tags: ["Long-term", "Full-time"], aiExposure: "Medium" },
  { id: "pangian", name: "Pangian", url: "https://pangian.com", category: "General Job Boards", type: "Work", description: "Global remote work board connecting a worldwide audience to borderless opportunities.", tags: ["Worldwide", "Community"], aiExposure: "Medium" },
  { id: "powertofly", name: "PowerToFly", url: "https://powertofly.com", category: "General Job Boards", type: "Work", description: "Diversity-focused hiring platform explicitly targeting women in tech and remote roles.", tags: ["Women in Tech", "Diversity"], aiExposure: "Medium" },
  { id: "themomproject", name: "The Mom Project", url: "https://themomproject.com", category: "General Job Boards", type: "Work", description: "Dedicated to keeping mothers in the workforce through flexible, remote, and family-friendly roles.", tags: ["Mothers", "Flexible"], aiExposure: "Low" },
  
  // NON-TECH / SUPPORT / VA
  { id: "belay", name: "Belay", url: "https://belay.com", category: "Non-Tech / Support / VA", type: "Work", description: "Premium virtual assistant platform for US-based workers matching VAs with executives.", tags: ["Premium VA", "US Focus"], aiExposure: "Medium" },
  { id: "timeetc", name: "Time Etc", url: "https://timeetc.com", category: "Non-Tech / Support / VA", type: "Work", description: "UK/US focused virtual assistant platform founded by a former executive.", tags: ["Assistant", "Experienced"], aiExposure: "Medium" },
  { id: "fancyhands", name: "Fancy Hands", url: "https://fancyhands.com", category: "Non-Tech / Support / VA", type: "Work", description: "Fast, task-based VA work ideal for piecing together micro-gigs. US focused.", tags: ["Task-based", "Micro-gig"], aiExposure: "High" },
  { id: "zirtual", name: "Zirtual", url: "https://zirtual.com", category: "Non-Tech / Support / VA", type: "Work", description: "Providing dedicated virtual assistants to entrepreneurs and small businesses.", tags: ["Dedicated VA", "Administrative"], aiExposure: "Medium" },
  { id: "horkeyhandbook", name: "Horkey Handbook", url: "https://horkeyhandbook.com", category: "Non-Tech / Support / VA", type: "Work", description: "VA training hub combined with a job board. Excellent for zero-experience beginners.", tags: ["Training Provided", "Beginners"], aiExposure: "Low" },
  { id: "smithai", name: "Smith.ai", url: "https://smith.ai", category: "Non-Tech / Support / VA", type: "Work", description: "Virtual receptionists handling inbound leads, calls, and scheduling. Paid training provided.", tags: ["Receptionist", "Training"], aiExposure: "Medium" },
  { id: "supportdriven", name: "Support Driven", url: "https://supportdriven.com", category: "Non-Tech / Support / VA", type: "Work", description: "Niche job board exclusively for customer support professionals and leadership.", tags: ["Customer Success", "Professional"], aiExposure: "Low" },
  { id: "workingsolutions", name: "Working Solutions", url: "https://workingsolutions.com", category: "Non-Tech / Support / VA", type: "Work", description: "Independent contractor roles offering on-demand customer service and sales processing.", tags: ["Contractor", "Customer Service"], aiExposure: "Medium" },
  { id: "liveops", name: "Liveops", url: "https://liveops.com", category: "Non-Tech / Support / VA", type: "Work", description: "Massive virtual call center. Pay is often per-minute/call for various major brands.", tags: ["Call Center", "Flexible"], aiExposure: "Medium" },
  { id: "arise", name: "Arise", url: "https://arise.com", category: "Non-Tech / Support / VA", type: "Work", description: "Customer service platform requiring you to register as a micro-business. Good for flexible heavy hours.", tags: ["Customer Service", "Business Setup"], aiExposure: "Medium" },
  { id: "alorica", name: "Alorica", url: "https://alorica.com", category: "Non-Tech / Support / VA", type: "Work", description: "Large global BPO hiring heavily for at-home customer service reps.", tags: ["BPO", "Entry Level"], aiExposure: "Medium" },
  { id: "transcom", name: "Transcom", url: "https://transcom.com", category: "Non-Tech / Support / VA", type: "Work", description: "Global customer experience provider offering widespread remote sales and support roles.", tags: ["Global Support", "CX"], aiExposure: "Medium" },
  { id: "sitel", name: "Foundever (Sitel)", url: "https://foundever.com", category: "Non-Tech / Support / VA", type: "Work", description: "Customer support behemoth handling thousands of remote workers globally.", tags: ["Enterprise Support", "Global"], aiExposure: "Medium" },
  
  // AI TRAINING / MICRO-TASK
  { id: "appen", name: "Appen", url: "https://appen.com", category: "AI Training & Micro-Task", type: "Work", description: "Global provider of AI training data. Projects range from search evaluation to audio transcription.", tags: ["Global Focus", "Training Data"], aiExposure: "Low" },
  { id: "clickworker", name: "Clickworker", url: "https://clickworker.com", category: "AI Training & Micro-Task", type: "Work", description: "Data entry, surveys, and app testing. Easy to register globally, though pay varies heavily.", tags: ["Micro-task", "Global"], aiExposure: "Low" },
  { id: "scaleai", name: "Scale AI", url: "https://scale.ai", category: "AI Training & Micro-Task", type: "Work", description: "High-quality data labeling and RLHF training. Extremely competitive but higher tier pay.", tags: ["RLHF", "Data Labeling"], aiExposure: "Low" },
  { id: "invisible", name: "Invisible Technologies", url: "https://invisible.co", category: "AI Training & Micro-Task", type: "Work", description: "Operates as a hybrid AI and human-in-the-loop task execution service for enterprise clients.", tags: ["Process Automation", "Human-in-loop"], aiExposure: "Low" },
  { id: "surgeai", name: "Surge AI", url: "https://surgehq.ai", category: "AI Training & Micro-Task", type: "Work", description: "Specialized AI data creation requiring domain experts in writing, math, and coding.", tags: ["Expert Trainers", "Generative AI"], aiExposure: "Low" },
  { id: "neevo", name: "Neevo", url: "https://neevo.ai", category: "AI Training & Micro-Task", type: "Work", description: "Help improve AI systems by performing simple audio, text, and image tasks globally.", tags: ["Simple Tasks", "Global"], aiExposure: "Low" },

  // WRITING & CREATIVE
  { id: "problogger", name: "ProBlogger Jobs", url: "https://problogger.com/jobs", category: "Writing & Creative", type: "Work", description: "The industry standard board for blogging jobs, copywriting, and content strategy.", tags: ["Blogging", "Copywriting"], aiExposure: "Medium" },
  { id: "freelancewritinggigs", name: "Freelance Writing Jobs", url: "https://freelancewritinggigs.com", category: "Writing & Creative", type: "Work", description: "Daily curated list of paid writing leads scoured from across the internet.", tags: ["Daily Leads", "Free Database"], aiExposure: "High" },
  { id: "mediabistro", name: "MediaBistro", url: "https://mediabistro.com", category: "Writing & Creative", type: "Work", description: "Premium job board for media professionals, ranging from editorial to television production.", tags: ["Media", "Editorial"], aiExposure: "Medium" },
  { id: "writeraccess", name: "WriterAccess", url: "https://writeraccess.com", category: "Writing & Creative", type: "Work", description: "Content marketplace matching vetted writers, editors, and translators with agencies.", tags: ["Marketplace", "Vetted Writers"], aiExposure: "High" },
  { id: "behancejobs", name: "Behance Jobs", url: "https://behance.net/joblist", category: "Writing & Creative", type: "Work", description: "Adobe's official job board integrated with portfolios. Amazing for discovering creative work.", tags: ["Portfolios", "Design"], aiExposure: "Low" },
  { id: "coroflot", name: "Coroflot", url: "https://coroflot.com", category: "Writing & Creative", type: "Work", description: "Specialized in industrial design, 3D modeling, and physical product creatives.", tags: ["Industrial Design", "3D"], aiExposure: "Low" },
  { id: "artstation", name: "ArtStation Jobs", url: "https://artstation.com/jobs", category: "Writing & Creative", type: "Work", description: "The premier board for gaming, entertainment, and visual effects artists.", tags: ["Gaming", "Entertainment"], aiExposure: "Low" },
  { id: "krop", name: "Krop", url: "https://krop.com", category: "Writing & Creative", type: "Work", description: "Creative industry job board highly focused on portfolio presentation and agency matching.", tags: ["Agencies", "Portfolio"], aiExposure: "Medium" },

  // TECH & DEVELOPMENT
  { id: "gunio", name: "Gun.io", url: "https://gun.io", category: "Tech & Development", type: "Work", description: "Premium platform for highly experienced senior developers and software engineers.", tags: ["Senior Devs", "Vetted"], aiExposure: "Medium" },
  { id: "lemonio", name: "Lemon.io", url: "https://lemon.io", category: "Tech & Development", type: "Work", description: "Connects vetted Eastern European and global developers with fast-growing startups.", tags: ["Vetted", "Startups"], aiExposure: "Low" },
  { id: "turing", name: "Turing", url: "https://turing.com", category: "Tech & Development", type: "Work", description: "AI-backed matching platform finding long-term remote roles for top-tier engineers.", tags: ["AI-Matched", "Long-term"], aiExposure: "Medium" },
  { id: "authenticjobs", name: "Authentic Jobs", url: "https://authenticjobs.com", category: "Tech & Development", type: "Work", description: "Long-standing board for hackers, designers, and creative professionals.", tags: ["Web Pros", "Established"], aiExposure: "Medium" }
];

// Deduplicate existing entries
const existingIds = new Set(currentData.map(p => p.id));
const filteredNew = newPlatforms.filter(p => !existingIds.has(p.id));

const mergedData = [...currentData, ...filteredNew];

fs.writeFileSync(dataPath, JSON.stringify(mergedData, null, 2), 'utf8');
console.log(`Successfully added ${filteredNew.length} new curated platforms! Current total: ${mergedData.length}`);
